name: simple_weather
description: "Simple weather app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc_concurrency: ^0.2.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProRounded
      fonts:
        - asset: assets/fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Rounded-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Rounded-Bold.ttf
          weight: 700